version: '3'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: zabbix
      MARIADB_USER: zabbix
      MARIADB_PASSWORD: zabbix
    networks:
      - zabbix-grafana-net

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    environment:
      DB_SERVER_HOST: mariadb
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
    ports:
      - "10051:10051"
    depends_on:
      - mariadb
    networks:
      - zabbix-grafana-net

  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:latest
    environment:
      DB_SERVER_HOST: mariadb
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
      ZBX_SERVER_HOST: zabbix-server
    ports:
      - "8080:80"
    depends_on:
      - zabbix-server
    networks:
      - zabbix-grafana-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    networks:
      - zabbix-grafana-net

networks:
  zabbix-grafana-net:
    external: true